# Generated by Django 4.2.7 on 2023-11-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('profile', models.IntegerField(choices=[(1, 'Buyer'), (2, 'Seller')])),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.emails')),
            ],
        ),
    ]
