# Generated by Django 4.2.7 on 2023-11-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_buyer_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyer',
            new_name='Profile',
        ),
    ]
