# Generated by Django 4.2.7 on 2023-11-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_rename_profile_profilebuyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profilebuyer',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profilebuyer',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profilebuyer',
            name='surname',
            field=models.CharField(max_length=20),
        ),
    ]
