# Generated by Django 4.2.7 on 2023-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_alter_emails_email_alter_profilebuyer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_catalog', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
