# Generated by Django 4.2.7 on 2023-12-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_catalogs_alter_emails_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalogs',
        ),
    ]
