# Generated by Django 4.2.7 on 2023-12-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_catalog_catalogproduct_profileseller_store_name_and_more'),
        ('buyer', '0007_delete_catalogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emails',
            new_name='Email',
        ),
    ]
