# Generated by Django 4.2.7 on 2023-12-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_rename_emails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebuyer',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
