# Generated by Django 4.2.7 on 2023-12-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_alter_profilebuyer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilebuyer',
            name='token',
            field=models.CharField(default=None),
        ),
    ]
