# Generated by Django 4.2.7 on 2023-12-18 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_profilebuyer_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilebuyer',
            name='token',
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.email')),
            ],
        ),
    ]
