# Generated by Django 4.2.7 on 2023-12-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0011_remove_profilebuyer_token_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilebuyer',
            name='active_account',
            field=models.BooleanField(default=False),
        ),
    ]
