# Generated by Django 4.2.7 on 2023-12-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0013_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='stop_date',
            field=models.DateTimeField(default=None),
        ),
    ]
