# Generated by Django 4.2.7 on 2023-12-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0014_token_stop_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebuyer',
            name='password',
            field=models.BinaryField(),
        ),
    ]
