# Generated by Django 4.2.7 on 2023-12-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0015_alter_profilebuyer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebuyer',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
