# Generated by Django 4.2.7 on 2023-12-19 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0016_alter_profilebuyer_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='TokenEmail',
        ),
        migrations.CreateModel(
            name='TokenMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_main', models.CharField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.email')),
            ],
        ),
    ]
