# Generated by Django 4.2.7 on 2023-12-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0018_shoppingcart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenemail',
            name='stop_date',
        ),
    ]
