# Generated by Django 4.2.7 on 2023-12-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0019_remove_tokenemail_stop_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenemail',
            name='stop_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='tokenmain',
            name='stop_date',
            field=models.DateTimeField(default=None),
        ),
    ]
