# Generated by Django 4.2.7 on 2024-01-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0021_rename_token_tokenemail_token_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[(1, 'Buyer'), (2, 'Seller')])),
            ],
        ),
        migrations.AddField(
            model_name='profilebuyer',
            name='profile_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='buyer.profiletype'),
        ),
    ]
