# Generated by Django 4.2.7 on 2024-01-22 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0022_profiletype_profilebuyer_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebuyer',
            name='profile_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buyer.profiletype'),
        ),
    ]
