# Generated by Django 4.2.7 on 2024-01-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0024_remove_profilebuyer_profile_type_delete_profiletype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenemail',
            old_name='token_email',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='tokenmain',
            old_name='token_main',
            new_name='token',
        ),
    ]
