# Generated by Django 4.2.7 on 2024-01-31 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0026_remove_shoppingcart_id_alter_shoppingcart_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebuyer',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buyer.email'),
        ),
    ]
