# Generated by Django 4.2.7 on 2024-02-01 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0028_tokenbuyer_delete_tokenmain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenbuyer',
            name='profile_buyer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='buyer.profilebuyer'),
            preserve_default=False,
        ),
    ]
