# Generated by Django 4.2.7 on 2024-02-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0029_tokenbuyer_profile_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenbuyer',
            old_name='profile_buyer',
            new_name='profile',
        ),
    ]
