# Generated by Django 4.2.7 on 2024-02-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0031_tokenemailbuyer_delete_tokenemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenbuyer',
            name='token',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tokenemailbuyer',
            name='token',
            field=models.CharField(max_length=254),
        ),
    ]
