# Generated by Django 4.2.7 on 2024-02-29 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0032_alter_tokenbuyer_token_alter_tokenemailbuyer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebuyer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profilebuyer',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buyer.profilebuyer'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tokenbuyer',
            name='stop_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tokenemailbuyer',
            name='stop_date',
            field=models.DateTimeField(),
        ),
    ]
