# Generated by Django 4.2.7 on 2024-03-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0033_alter_profilebuyer_name_alter_profilebuyer_surname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenEmailBuyer',
        ),
    ]
