# Generated by Django 4.2.7 on 2024-03-15 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0035_delete_tokenbuyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.profilebuyer'),
        ),
    ]
