# Generated by Django 4.2.7 on 2024-03-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0025_delete_tokenseller'),
        ('buyer', '0036_alter_shoppingcart_buyer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='buyer',
            new_name='buyer_profile',
        ),
        migrations.AddField(
            model_name='profilebuyer',
            name='shop',
            field=models.ManyToManyField(through='buyer.Order', to='seller.product'),
        ),
    ]
