# Generated by Django 4.2.7 on 2024-03-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0037_rename_shoppingcart_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buyer_profile',
            new_name='buyer',
        ),
    ]
