# Generated by Django 4.2.7 on 2023-11-16 10:03

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer', '0004_rename_profile_profilebuyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Individual_Taxpayer_Number', models.CharField(max_length=12)),
                ('type_of_organization', models.IntegerField(choices=[('ИП', 'Индивидуальный предприниматель'), ('ООО', 'Общество с Ограниченной Ответственностью')])),
                ('country_of_registration', django_countries.fields.CountryField(max_length=2)),
                ('password', models.CharField(max_length=150)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.emails')),
            ],
        ),
    ]
