# Generated by Django 4.2.7 on 2023-11-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileseller',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
