# Generated by Django 4.2.7 on 2023-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_profileseller_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileseller',
            name='type_of_organization',
            field=models.CharField(choices=[('ИП', 'Индивидуальный предприниматель'), ('ООО', 'Общество с Ограниченной Ответственностью')]),
        ),
    ]
