# Generated by Django 4.2.7 on 2023-12-01 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_profileseller_type_of_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_catalog', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.catalog')),
            ],
        ),
        migrations.AddField(
            model_name='profileseller',
            name='store_name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_product', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40)),
                ('quantity', models.CharField(max_length=40)),
                ('catalogs', models.ManyToManyField(through='seller.CatalogProduct', to='seller.catalog')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.profileseller')),
            ],
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
    ]
