# Generated by Django 4.2.7 on 2023-12-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_catalog_catalogproduct_profileseller_store_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catalogs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store_name',
        ),
        migrations.AlterField(
            model_name='profileseller',
            name='store_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.DeleteModel(
            name='CatalogProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
