# Generated by Django 4.2.7 on 2023-12-01 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_remove_product_catalogs_remove_product_store_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_product', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40)),
                ('quantity', models.CharField(max_length=40)),
                ('catalogs', models.ManyToManyField(through='seller.CatalogProduct', to='seller.catalog')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.profileseller')),
            ],
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
    ]
