# Generated by Django 4.2.7 on 2023-12-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
