# Generated by Django 4.2.7 on 2024-01-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_profileseller_profile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileseller',
            name='profile_type',
        ),
    ]
