# Generated by Django 4.2.7 on 2024-01-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_remove_profileseller_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileseller',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
