# Generated by Django 4.2.7 on 2024-01-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_alter_profileseller_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileseller',
            name='active_account',
            field=models.BooleanField(default=False),
        ),
    ]
