# Generated by Django 4.2.7 on 2024-01-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_profileseller_active_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_product',
            field=models.CharField(max_length=100),
        ),
    ]
