# Generated by Django 4.2.7 on 2024-01-31 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0027_alter_profilebuyer_email'),
        ('seller', '0014_alter_product_description_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileseller',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buyer.email'),
        ),
    ]
