# Generated by Django 4.2.7 on 2024-02-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0015_alter_profileseller_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField()),
                ('stop_date', models.DateTimeField(default=None)),
            ],
        ),
    ]
