# Generated by Django 4.2.7 on 2024-02-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_tokenseller_profileseller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenseller',
            old_name='ProfileSeller',
            new_name='profile',
        ),
    ]
