# Generated by Django 4.2.7 on 2024-02-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0019_tokenemailseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
