# Generated by Django 4.2.7 on 2024-03-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0023_alter_catalog_title_catalog_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenEmailSeller',
        ),
    ]
