# Generated by Django 4.2.7 on 2024-03-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0024_delete_tokenemailseller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenSeller',
        ),
    ]
